In [1]:
import numpy as np

# Q1  Create a Python list representing vector v = [2, -1, 3] and multiply it by scalar 4.


In [2]:
# 1. Show the output
V = [2, -1, 3]
result = V * 4
result

[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]

2. in linear algebra it must be [8, -4, 12], but we get repeatition of our list

In [3]:
# 3. . Convert the vector to a NumPy array and repeat the operation.
v = np.array(V)
result = v * 4
result

array([ 8, -4, 12])

# Q2 Given vector a = [5, -3] and scalar $\lambda$ = -2

In [4]:
a = np.array([5, -3])
lambda_ = -2

# 1. Compute $\lambda$ a

result = lambda_ * a
print(f"lambda * a = {result}")

# 2. Compare their magnitudes
print(f"||a|| = {np.linalg.norm(a)}")
print(f"||result|| = {np.linalg.norm(result)}")

lambda * a = [-10   6]
||a|| = 5.830951894845301
||result|| = 11.661903789690601



#### 3. Explain the effect on magnitude and direction.
1. magnitude multiplies by |$\lambda$|
2. direction change if $\lambda$ < 0

# Q3. Create:

In [5]:
# Column vector shape (3, 1)
c_v = np.array([[1], [2], [3]])
print(f"column vector shape = {c_v.shape}")

# Row vector shape (1,4)
r_v = np.array([[1, 2, 3, 4]])
print(f"row vector shape = {r_v.shape}")

result = c_v + r_v
print(result)

column vector shape = (3, 1)
row vector shape = (1, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


# Q4 . Create vector v = [1,2,3,4] and add scalar 5.

In [6]:
v = np.array([1, 2, 3, 4])
result = v * 5
print(result)

[ 5 10 15 20]


NumPy do broadcast, it converts scalar into vector:  5 -> [5, 5, 5, 5]

# Q5. Given vector a = [1,2,3,4,5,6], compute its Euclidean norm manually and using NumPy.


In [19]:
a = np.array([1, 2, 3, 4, 5, 6])

c_sum = 0

for i in a:
    c_sum += i**2
print(c_sum**0.5)

manual = np.sqrt(np.sum(a**2))
print(manual)

norm = np.linalg.norm(a)
print(norm)

9.539392014169456
9.539392014169456
9.539392014169456


# Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization

In [8]:
v = np.random.rand(10)

before_norm = np.linalg.norm(v)

v_norm = v / before_norm

after_norm = np.linalg.norm(v_norm)
print(before_norm, after_norm, sep='\n')

1.6908757485246115
0.9999999999999999


# Q7. Compute the dot product of vectors

In [9]:
a = [1, 2, 3, 4, 5, 6]
b = [0, -4, 3, -3, 6, 5]

# Manual loop
man_res = 0
for i in range(len(a)):
    man_res += a[i] * b[i]
print(man_res)

np.dot(a, b)

49


np.int64(49)

# Q8. Verify the distributive property:

In [10]:
a = np.random.rand(3)
b = np.random.rand(3)
c = np.random.rand(3)

left = np.dot(a, b + c)
right = np.dot(a, b) + np.dot(a, c)
print(left, right, sep=' = ')

2.5210398131543696 = 2.5210398131543696


# Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.

In [21]:
# Group A
A = np.array([
 [ 2, 1],
 [ 5, 4],
 [ 1, 6],
 [ 7, 2]
]) 
# Group B
B = np.array([
 [0, 0],
 [6, 3],
 [3, 5]
])

A_n = A[:, None, :]
B_n = B[None, :, :]

dist = np.sqrt(((A_n - B_n) ** 2).sum(axis=2))
print(A_n - B_n)
dist

[[[ 2  1]
  [-4 -2]
  [-1 -4]]

 [[ 5  4]
  [-1  1]
  [ 2 -1]]

 [[ 1  6]
  [-5  3]
  [-2  1]]

 [[ 7  2]
  [ 1 -1]
  [ 4 -3]]]


array([[2.23606798, 4.47213595, 4.12310563],
       [6.40312424, 1.41421356, 2.23606798],
       [6.08276253, 5.83095189, 2.23606798],
       [7.28010989, 1.41421356, 5.        ]])